spring:
  application:
    name: heroarena
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    port: '587'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  accessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
  refreshTokenKey: ${JWT_REFRESH_TOKEN_KEY}
  accessTokenExpires: 1800000
  refreshTokenExpires: 259200000